CFLAGS += -Ift_readline -Ift_readline/libft
SOURCES += 	ft_readline/libft/ft_strtrim.c \
			ft_readline/libft/ft_tolower.c \
			ft_readline/libft/ft_memdel.c \
			ft_readline/libft/ft_strcpy.c \
			ft_readline/libft/ft_isalnum.c \
			ft_readline/libft/ft_memmove.c \
			ft_readline/libft/ft_striter.c \
			ft_readline/libft/ft_strmapi.c \
			ft_readline/libft/ft_atoi.c \
			ft_readline/libft/ft_lstmap.c \
			ft_readline/libft/ft_putstr_fd.c \
			ft_readline/libft/ft_bzero.c \
			ft_readline/libft/ft_freejoin.c \
			ft_readline/libft/ft_putstr.c \
			ft_readline/libft/ft_striteri.c \
			ft_readline/libft/ft_putendl.c \
			ft_readline/libft/ft_itoa.c \
			ft_readline/libft/ft_strmap.c \
			ft_readline/libft/ft_strnstr.c \
			ft_readline/libft/ft_strncmp.c \
			ft_readline/libft/ft_memcmp.c \
			ft_readline/libft/ft_strdel.c \
			ft_readline/libft/ft_strjoin.c \
			ft_readline/libft/ft_strequ.c \
			ft_readline/libft/ft_memcpy.c \
			ft_readline/libft/ft_strnew.c \
			ft_readline/libft/ft_strsplit.c \
			ft_readline/libft/ft_putchar.c \
			ft_readline/libft/ft_strncpy.c \
			ft_readline/libft/ft_strcmp.c \
			ft_readline/libft/ft_strlcat.c \
			ft_readline/libft/ft_strdup.c \
			ft_readline/libft/ft_isascii.c \
			ft_readline/libft/ft_memalloc.c \
			ft_readline/libft/ft_strsub.c \
			ft_readline/libft/ft_memset.c \
			ft_readline/libft/ft_strclr.c \
			ft_readline/libft/ft_isalpha.c \
			ft_readline/libft/ft_lstnew.c \
			ft_readline/libft/ft_lstdelone.c \
			ft_readline/libft/ft_strncat.c \
			ft_readline/libft/ft_strnequ.c \
			ft_readline/libft/ft_strlen.c \
			ft_readline/libft/ft_memchr.c \
			ft_readline/libft/ft_lstdel.c \
			ft_readline/libft/ft_freedup.c \
			ft_readline/libft/ft_putnbr.c \
			ft_readline/libft/ft_putnbr_fd.c \
			ft_readline/libft/ft_memccpy.c \
			ft_readline/libft/ft_strstr.c \
			ft_readline/libft/ft_lstiter.c \
			ft_readline/libft/ft_strrchr.c \
			ft_readline/libft/ft_putchar_fd.c \
			ft_readline/libft/ft_toupper.c \
			ft_readline/libft/ft_putendl_fd.c \
			ft_readline/libft/ft_isdigit.c \
			ft_readline/libft/ft_strchr.c \
			ft_readline/libft/ft_isprint.c \
			ft_readline/libft/ft_strcat.c \
			ft_readline/libft/ft_lstadd.c \
			\
			ft_readline/ft_add_to_history.c \
			ft_readline/ft_add_to_tmp.c \
			ft_readline/ft_free_match.c \
			ft_readline/ft_get_line.c \
			ft_readline/ft_get_line_save.c \
			ft_readline/ft_history_check.c \
			ft_readline/ft_history_find.c \
			ft_readline/ft_history_get_tory.c \
			ft_readline/ft_move_backslash.c \
			ft_readline/ft_move_begin_end.c \
			ft_readline/ft_move_cursor.c \
			ft_readline/ft_move_cursor_left.c \
			ft_readline/ft_move_cursor_right.c \
			ft_readline/ft_move_history.c \
			ft_readline/ft_move_line.c \
			ft_readline/ft_move_line_down.c \
			ft_readline/ft_move_tab.c \
			ft_readline/ft_move_word_right.c \
			ft_readline/ft_move_words.c \
			ft_readline/ft_parse_args.c \
			ft_readline/ft_signals.c \
			ft_readline/ft_start.c \
			ft_readline/ft_tab_cut.c \
			ft_readline/ft_tab_find_file.c \
			ft_readline/ft_tab_match_get.c \
			ft_readline/ft_tab_print_match.c \
			ft_readline/ft_tab_try_to_paste.c \
